// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Prodify.Infrastructure.Persistence;

#nullable disable

namespace Prodify.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ProdifyDbContext))]
    [Migration("20260930172427_ProductReviews")]
    partial class ProductReviews
    {
    }
}
