// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Prodify.Infrastructure.Persistence;

#nullable disable

namespace Prodify.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ProdifyDbContext))]
    [Migration("20261005074116_SellerPayouts")]
    partial class SellerPayouts
    {
    }
}
